version: '3.7'
services:
  discovery:
    image: biro/discovery_app
    ports:
      - '8761:8761'

  db:
    image: postgres
    restart: always
    env_file:
        - database.env
    volumes:
        # execute script .sh or .sql at first run
        - ./database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
        # save db data on host
        - ./postgres-data:/var/lib/postgresql/data
    ports:
        - '5439:5432'

  log:
    image: biro/log_app
    ports:
      - '8081:8080'