-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
-- BEGIN;

-- Database: rbac

-- DROP DATABASE IF EXISTS rbac;

-- CREATE DATABASE rbac
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'Italian_Italy.1252'
--     LC_CTYPE = 'Italian_Italy.1252'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SEQUENCE IF NOT EXISTS log_data_id_seq;

CREATE TABLE IF NOT EXISTS public.log_data
(
    id integer NOT NULL DEFAULT nextval('log_data_id_seq'::regclass),
    date TIMESTAMP NOT NULL,
    origin character varying COLLATE pg_catalog."default",
    message json NOT NULL,
    CONSTRAINT log_data_pkey PRIMARY KEY (id)
    );

END;
